### ISSUE TITLE
vue项目迁移过程采坑

### ISSUE THREAD

**Issue by eyea** [eyea/daily-grocery#57]
一、pr(750) --> 750px
旧项目使用自定义工具比如:
```css
// pr2rem.css
@function pr($px, $base: 75) {
    @return ($px / $base) *1rem;
}
// other scss
div {
  width: pr(430);
}
```
新项目迁移使用插件 __postcss-px2rem__
```css
div {
  width: 430px;
}
```
假设都基于750px的设计稿进行开发
如何批量替换单位呢？

Answer1：使用编辑器的批量替换功能
Answer2：正则 TODO?
